development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: twilio-try1
  pool: 5
  username: postgres
  password: postgres
  timeout: 5000


production:
  host: firstass
  adapter: postgresql
  encoding: unicode
  database: twilio-try1
  pool: 5
  username: postgres
  password: postgres
  timeout: 5000



